<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEgxfwkx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEgxfwkx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEgxfwkx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEgxfwkx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEgxfwkx\appProdProjectContainer([
    'container.build_hash' => 'Egxfwkx',
    'container.build_id' => '566bad5d',
    'container.build_time' => 1560331291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEgxfwkx');
